libgssglue: update SRC_URI
Issue: LIN1021-217

Update SRC_URI to use Debian mirror because the original site is
unaccessible.

Fixes do_fetch error:
ERROR: libgssglue-0.4-r0 do_fetch: Fetcher failure for URL:
'http://www.citi.umich.edu/projects/nfsv4/linux/libgssglue/libgssglue-0.4.tar.gz'.
Unable to fetch URL from any source.

(LOCAL REV: NOT UPSTREAM) -- Sent to meta-security on 20210524

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>